# Generated by Django 6.0.4 on 2026-04-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Birthday Package', 'Birthday Package'), ('Marriage Package', 'Marriage Package'), ('Office Party Package', 'Office Party Package'), ('Bachelor Party Package', 'Bachelor Party Package'), ('Custom Combo Package', 'Custom Combo Package')], max_length=100)),
                ('package_name', models.CharField(max_length=150)),
                ('included_services', models.TextField()),
                ('description', models.TextField()),
                ('total_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
