# Generated by Django 6.0.4 on 2026-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_profile_bio_profile_cover_image_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
