# Generated by Django 6.0.4 on 2026-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_notification_booking_id_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
