# Generated by Django 6.0.4 on 2026-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_profile_auto_accept_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
