# Generated by Django 6.0.4 on 2026-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_profile_business_certificate_profile_fssai_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
