# Generated by Django 6.0.4 on 2026-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_service_extra_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_booking_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='advance_payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='availability_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='min_booking_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
