# Generated by Django 6.0.4 on 2026-05-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_booking_extra_booking_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='availability_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='package',
            name='location_coverage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='max_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pricing_structure',
            field=models.CharField(default='Fixed Price', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='variants',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_gallery/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.package')),
            ],
        ),
    ]
