# Generated by Django 6.0.4 on 2026-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='occasion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
