# Generated by Django 6.0.4 on 2026-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_package_discount_percentage_package_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
