# Generated by Django 6.0.4 on 2026-05-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_profile_admin_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
